name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure --prefix=$HOME/usr
    - name: make j8
      run: make -j8
    - name: make install
      run: make install
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: artifact
        path: /home/runner/work/httrack
        if-no-files-found: warn

